### ISSUE TITLE
Any interest with combining with areal aggregation

### ISSUE THREAD

**Issue by fgregg** [datadesk/census-data-aggregator#10]
Some folks at @argo-marketplace were working on a fork of census_area to aggregate census data to arbitrary geographies: https://github.com/datamade/census_area/issues/6

**Comment by palewire** [comment]
We've got this cooking already at the block level, which I think is in the ballpark.

https://github.com/datadesk/census-map-consolidator

**Comment by fgregg** [comment]
that seems like only need a pretty small step!

**Comment by palewire** [comment]
Yes. We will live this dream.
