### ISSUE TITLE
Source data for approximating median household income

### ISSUE THREAD

**Issue by ghing** [datadesk/census-data-aggregator#26]
Just to make sure I understand this correctly, to calculate median household income for an aggregate geography using the ACS, as shown in [this example](https://github.com/datadesk/census-data-aggregator#approximating-medians), would I use data from a table like ACS table B19001 to get the n (household counts), and min/max incomes for the ranges?

It looks like the wording of the top range of [that table](https://censusreporter.org/tables/B19001/) is "$200,000 or more". Should I just set an artificial upper bound for that? It looks like in the example and the [linked PDF](https://www.documentcloud.org/documents/6165014-How-to-Recalculate-a-Median.html), they use $250,001.

Off the top of my head, this seems like it would be correct for many (most?) cases, but incorrect for very high income areas?

**Comment by palewire** [comment]
Yes, you really have no choice. Something has to be used. We recommend experimenting with different lower and upper bounds to assess its effect on the result.
